### ISSUE TITLE
Add flag for turning off/on highlighting paths on mouseover

### ISSUE THREAD

**Issue by Tehsurfer** [AnatomicMaps/flatmap-viewer#18]
I'd like to use the `highlightFeatures()` api for the the 'show connected paths' tool, as it keeps the colours of the paths. 

However currently, the mouseover events override the highlighting as soon as the cursor moves.

Would be great to have a way to turn the highlighting of paths from mouseover on/off

**Comment by dbrnz** [comment]
Just clarifying, it is only paths that you don't want highlighting? The original PR was trying to address all features, not just paths.

And I'm still not sure exactly what you want, esp. as the notion of `highlighted` has variously meant `selected` or `activated` as the software has evolved. Forgetting about what`highlightFeatures()` currently does, is what happens when you click on a path something like what you are after??

**Comment by Tehsurfer** [comment]
> Just clarifying, it is only paths that you don't want highlighting

Yep, want a flag to turn on/off the highlighting on mouseover

**Comment by Tehsurfer** [comment]
I'll send a video on slack so you can see what I'm talking about
