### ISSUE TITLE
Minimap appears blank occasionally

### ISSUE THREAD

**Issue by alan-wu** [AnatomicMaps/flatmap-viewer#36]
Minimap on flatmaps may appear blank when width and height are specified in the maplibregl-ctrl-minimap class. The dimension of the original display seems to play a role as well.

**Comment by dbrnz** [comment]
This is because for certain container sizes, the minimap is assigned a zoom level less than 2, yet all our maps are built with min-zoom set to 2.

The fix is to regenerate the maps with a lower min-zoom, which I'm about to do so, and am closing this issue.

The blue centrelines showing on the minimap is a separate issue, covered by #37.
